typography_spectrum: 0.7315469647292048
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.618600619956851
  lightness: 0.7229606241453439
  saturation: 0.5677816839888692
  rhythmicContrast: 0.23712968244217336
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8803554612677544
analytics:
  google: null
  facebook: null
  twitter: null
name: IdealProject
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Fitnesscracia
purpose: []
